version: '3.8'
services:
  frontend:
    build: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      # - redis
      - backend

  backend:
    build: ./backend
    ports:
      - "5001:5001"
    # depends_on:
    #   - redis

  # redis:
  #   image: "redis:alpine"
  #   ports:
  #     - "6379:6379"
